version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd react-app/
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files: 
    - '**/*'
  base-directory: 'react-app/build'